name: 'VTEX Toolbelt Login'
description: 'Perform login using VTEX Toolbelt with supplied credentials'
author: VTEX
inputs:
  account:
    required: true
    description: 'Account to perform login on'
  app-key:
    required: true
    description: 'APP Key used in authentication'
  app-token:
    required: true
    description: 'APP Token used in authentication'
runs:
  using: 'node16'
  main: 'dist/index.js'
